name: CI

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: |
          cd packages/server
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run quality checks
        run: |
          cd packages/server
          composer qual

  front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd packages/front
          pnpm install

      - name: Lint code
        run: |
          cd packages/front
          pnpm lint
